// Updated FinalPreviewPublish.jsx
import React from "react";
import { FileText, CheckCircle } from "lucide-react";

const FinalPreviewPublish = ({ testData }) => {
  if (!testData) {
    return (
      <div className="bg-[#FDF2FF] rounded-2xl p-8 text-center">
        <p className="text-gray-500">No test data available</p>
      </div>
    );
  }

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  };

  const hasAnswerKey = testData.answerPdfUrl && testData.answerPdfUrl.trim() !== '';

  return (
    <div className="bg-[#FDF2FF] rounded-2xl p-5 sm:p-6 md:p-8 w-full">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* Left Section */}
        <div className="lg:border-r-2 border-purple-200 lg:pr-8">
          <div className="text-[#B11D8C] text-sm sm:text-base font-medium mb-4">
            {formatDate(testData.testDate)} • {testData.startTime}
          </div>

          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 sm:mb-6 leading-snug">
            {testData.subjectName} {testData.testCategory}
          </h1>

          <div className="space-y-3 text-[#727272]">
            <div className="flex flex-wrap items-center gap-2 sm:gap-3 text-lg sm:text-xl">
              <span>{testData.numberOfQuestions} Questions</span>
              <span>•</span>
              <span>Duration: {testData.duration} minutes</span>
            </div>

            <div className="pt-1 text-lg sm:text-xl">
              <div>
                Department: <span className="text-[#727272]">{testData.department}</span>
              </div>
              <div>
                Semester: <span className="text-[#727272]">{testData.semester}</span>
              </div>
              <div>
                Subject Code: <span className="text-[#727272]">{testData.subjectCode}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Right Section */}
        <div className="space-y-6">
          
          {/* Questions Section */}
          <div>
            <h2 className="text-2xl font-bold text-[#2A1B32] mb-4">Questions</h2>

            <div className="bg-gradient-to-r from-green-50 to-emerald-50 border-2 border-green-200 rounded-xl p-4 flex items-center gap-4">
              <div className="bg-red-500 rounded-lg p-3 flex-shrink-0">
                <FileText className="w-6 h-6 text-white" />
              </div>

              <div className="flex-grow min-w-0">
                <div className="font-medium text-gray-900 truncate">
                  Question Paper
                </div>
                <div className="text-sm text-gray-600">Uploaded</div>
              </div>

              <CheckCircle className="w-6 h-6 text-green-500 flex-shrink-0" />
            </div>
          </div>

          {/* Answers Section */}
          {hasAnswerKey ? (
            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Answers</h2>

              <div className="bg-gradient-to-r from-green-50 to-emerald-50 border-2 border-green-200 rounded-xl p-4 flex items-center gap-4">
                <div className="bg-red-500 rounded-lg p-3 flex-shrink-0">
                  <FileText className="w-6 h-6 text-white" />
                </div>

                <div className="flex-grow min-w-0">
                  <div className="font-medium text-gray-900 truncate">
                    Answer Key
                  </div>
                  <div className="text-sm text-gray-600">Uploaded by faculty</div>
                </div>

                <CheckCircle className="w-6 h-6 text-green-500 flex-shrink-0" />
              </div>
            </div>
          ) : (
            <div>
              <h2 className="text-2xl font-bold text-[#2A1B32] mb-4">Answers</h2>

              <div className="text-[#6A1B7E9E] italic text-lg sm:text-xl leading-relaxed">
                No answer key provided. <br className="hidden sm:block" />
                Answers generated by IEMA AI
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default FinalPreviewPublish; 