import React, { useState } from "react";
import { FileText, CheckCircle } from "lucide-react";

const FinalPreviewPublish = () => {
  const [testInfo] = useState({
    date: "Nov 10",
    time: "10:00 AM",
    title: "Machine Learning Mid-Sem Test",
    questions: 30,
    marks: 60,
    duration: "1 hour",
    department: "CST",
    semester: "05",
  });

  const [pdfInfo] = useState({
    name: "Machine_learning_midsem5.pdf",
    size: "5.3MB",
    uploaded: true,
  });

  const [answersGenerated] = useState(false);

  return (
    <div className="bg-[#FDF2FF] rounded-2xl p-5 sm:p-6 md:p-8 w-full">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* Left Section */}
        <div className="lg:border-r-2 border-purple-200 lg:pr-8">
          <div className="text-[#B11D8C] text-sm sm:text-base font-medium mb-4">
            {testInfo.date} • {testInfo.time}
          </div>

          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-4 sm:mb-6 leading-snug">
            {testInfo.title}
          </h1>

          <div className="space-y-3 text-[#727272]">
            <div className="flex flex-wrap items-center gap-2 sm:gap-3 text-lg sm:text-xl">
              <span>{testInfo.questions} Questions</span>
              <span>•</span>
              <span>{testInfo.marks} Marks</span>
              <span>•</span>
              <span>Duration: {testInfo.duration}</span>
            </div>

            <div className="pt-1 text-lg sm:text-xl">
              <div>
                Department: <span className="text-[#727272]">{testInfo.department}</span>
              </div>
              <div>
                Semester: <span className="text-[#727272]">{testInfo.semester}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Right Section */}
        <div className="space-y-6">
          
          {/* Questions Section */}
          <div>
            <h2 className="text-2xl font-bold text-[#2A1B32] mb-4">Questions</h2>

            <div className="bg-gradient-to-r from-green-50 to-emerald-50 border-2 border-green-200 rounded-xl p-4 flex items-center gap-4">
              <div className="bg-red-500 rounded-lg p-3 flex-shrink-0">
                <FileText className="w-6 h-6 text-white" />
              </div>

              <div className="flex-grow min-w-0">
                <div className="font-medium text-gray-900 truncate">{pdfInfo.name}</div>
                <div className="text-sm text-gray-600">
                  {pdfInfo.size} - uploaded
                </div>
              </div>

              <CheckCircle className="w-6 h-6 text-green-500 flex-shrink-0" />
            </div>
          </div>

          {/* Answers Section */}
          {answersGenerated ? (
            <div>
              <h2 className="text-2xl font-bold text-gray-900 mb-4">Answers</h2>

              <div className="bg-gradient-to-r from-green-50 to-emerald-50 border-2 border-green-200 rounded-xl p-4 flex items-center gap-4">
                <div className="bg-red-500 rounded-lg p-3 flex-shrink-0">
                  <FileText className="w-6 h-6 text-white" />
                </div>

                <div className="flex-grow min-w-0">
                  <div className="font-medium text-gray-900 truncate">
                    Answer_key_generated.pdf
                  </div>
                  <div className="text-sm text-gray-600">Generated by IEMA AI</div>
                </div>

                <CheckCircle className="w-6 h-6 text-green-500 flex-shrink-0" />
              </div>
            </div>
          ) : (
            <div>
              <h2 className="text-2xl font-bold text-[#2A1B32] mb-4">Answers</h2>

              <div className="text-[#6A1B7E9E] italic text-lg sm:text-xl leading-relaxed">
                No answer key provided. <br className="hidden sm:block" />
                Answers generated by IEMA AI
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default FinalPreviewPublish;
